<!-- index.php  -->
<?php
session_start();
require_once '../../config/init.php';
require_once '../../config/config.php';

// Verificar si el usuario está autenticado y es un docente
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
  header("Location: " . LOGIN_URL);
  exit();
}

$conn = conectarDB();

$pageTitle = "Asignacion de estudiantes a UD";
// Construir la consulta base
$queryClases = "SELECT c.id, a.nombre AS asignatura,
  CONCAT( d.apellidos, ', ', d.nombres ) AS docente,
  CONCAT( pe.nombre_corto, ' - ', ci.id, ' - ', s.año ) AS seccion,
  pe.id AS programa_id,
  pe.nombre AS programa_nombre 
FROM clases AS c
  JOIN asignaturas AS a ON c.id_asignatura = a.id
  JOIN usuarios AS d ON c.id_docente = d.id
  JOIN secciones AS s ON c.id_seccion = s.id
  JOIN programas_estudio AS pe ON s.id_programa_estudio = pe.id
  JOIN ciclos AS ci ON s.id_ciclo = ci.id 
WHERE d.role = 'docente'
ORDER BY pe.nombre, a.nombre";

$resultClases = $conn->query($queryClases);

$conn->close();

// Inicio del contenido
ob_start();
?>
<div class="container-fluid mt-4">
  <h3 class="mb-4"><?= htmlspecialchars($pageTitle); ?></h3>

  <div class="row">

    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <span class="fw-bold"><i class="fas fa-chalkboard-teacher me-2"></i>Unidades didácticas</span>
        </div>
        <div class="card-body">
          <table id="clasesTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <tr>
                <th>Asignatura</th>
                <th>Docente</th>
                <th>Sección</th>
              </tr>
            </thead>
            <tbody>
              <?php while ($clase = $resultClases->fetch_assoc()): ?>
                <tr class="clase-item" data-clase-id="<?= $clase['id'] ?>">
                  <td><?= htmlspecialchars($clase['asignatura']) ?></td>
                  <td><?= htmlspecialchars($clase['docente']) ?></td>
                  <td><?= htmlspecialchars($clase['seccion']) ?></td>
                </tr>
              <?php endwhile; ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>



    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header fw-bold">
          <i class="fa-sharp fa-solid fa-screen-users"></i> Estudiantes de UD
        </div>
        <div class="card-body" id="listaEstudiantes">
          <span class="fw-semibold">Seleccione una UD para ver los estudiantes.</span>
          <table id="estudiantesTable" class="table table-striped table-bordered" style="width:100%">
            <thead>

              <!-- The header will be dynamically generated by JavaScript -->
            </thead>
            <tbody>
              <!-- The body will be dynamically populated by JavaScript -->
            </tbody>
          </table>


        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal para agregar estudiantes -->
<div class="modal fade" id="agregarEstudiantesModal" tabindex="-1" aria-labelledby="agregarEstudiantesModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="agregarEstudiantesModalLabel">Agregar Estudiantes</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table id="estudiantesDisponiblesTable" class="table table-striped table-bordered" style="width:100%">
          <thead>
            <!-- Será llenado dinámicamente -->
          </thead>
          <tbody>
            <!-- Será llenado dinámicamente -->
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="btnGuardarEstudiantes">Guardar</button>
      </div>
    </div>
  </div>
</div>

<?php
$content = ob_get_clean();

$pageStyles = '

';

$pageScripts = '

<script src="js/index.js"></script>

';

// Incluir el layout principal
require_once '../layouts/main.php';
?>