<?php
session_start();
require_once '../../config/init.php';
require_once '../../config/config.php';

// Verificar si el usuario está autenticado y es un estudiante
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'estudiante') {
  header("Location: " . LOGIN_URL);
  exit();
}

// Obtener información del estudiante
$conn = conectarDB();
$user_id = $_SESSION['user_id'];

// Obtener detalles del estudiante
$stmt = $conn->prepare("SELECT * FROM usuarios WHERE id = ? AND role = 'estudiante'");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$estudiante = $stmt->get_result()->fetch_assoc();
$fullNameEstudiante = $estudiante['apellidos'] . ', ' . $estudiante['nombres'];
?>

<script>
  window.phpData = {
    fullNameEstudiante: <?php echo json_encode($fullNameEstudiante); ?>
  };
</script>

<?php

// Obtener clases del estudiante
$stmt = $conn->prepare("
    SELECT c.id, a.nombre AS asignatura, CONCAT(d.apellidos, ', ', d.nombres) AS docente, 
    CONCAT(pe.nombre_corto, ' - ' , ci.id, ' - ', s.año) as seccion
    FROM estudiantes_clases ec
    JOIN clases c ON ec.id_clase = c.id
    JOIN asignaturas a ON c.id_asignatura = a.id
    JOIN usuarios d ON c.id_docente = d.id
    JOIN secciones s ON c.id_seccion = s.id
    JOIN ciclos ci ON s.id_ciclo = ci.id
    JOIN programas_estudio pe ON s.id_programa_estudio = pe.id
    WHERE ec.id_estudiante = ?
    ORDER BY s.año DESC, ci.nombre ASC, a.nombre ASC
");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$clases = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);

// Obtener ciclos y años únicos para los filtros
$ciclos = array_unique(array_column($clases, 'ciclo'));
$años = array_unique(array_column($clases, 'año'));
rsort($años);

$conn->close();

// Inicio del contenido
ob_start();
?>
<div class="container-fluid mt-4">
  <h1 class="mb-4">Bienvenido, <?php echo htmlspecialchars($fullNameEstudiante); ?></h1>

  <div class="row">

  <div class="col-md-6 mb-4">
  <div class="card">
    <div class="card-header">
      <i class="fas fa-book me-2"></i>Mis Clases
    </div>
    <div class="card-body">
      <table id="clasesTable" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>Unid. didáctica</th>
            <th>Sección</th>
            <th>Docente</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($clases as $clase): ?>
            <tr class="clase-item" data-clase-id="<?php echo $clase['id']; ?>">
              <td><?php echo htmlspecialchars($clase['asignatura']); ?></td>
              <td><?php echo htmlspecialchars($clase['seccion']); ?></td>
              <td><?php echo htmlspecialchars($clase['docente']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</div>

    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <i class="fas fa-clock me-2"></i>Asistencias
        </div>
        <div class="card-body" id="listaAsistencias">
        <span class="fw-semibold">Seleccione una UD para ver sus asistencias.</span>
          <table id="asistenciasTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
              </tr>
              <!-- The header will be dynamically generated by JavaScript -->
            </thead>
            <tbody>
              <!-- Los datos se cargarán dinámicamente aquí -->
            </tbody>
          </table>


        </div>

      </div>
    </div>
  </div>
</div>

<?php
$content = ob_get_clean();

$pageScripts = '
<script src="estudiantes-dashboard.js"></script>
';

// Incluir el layout principal
// $pageTitle = "Dashboard Estudiante";
require_once '../layouts/main.php';
?>