<!-- index.php  -->
<?php
session_start();
require_once '../../config/init.php';
require_once '../../config/config.php';

// Verificar si el usuario está autenticado y es un docente
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'docente') {
  header("Location: " . LOGIN_URL);
  exit();
}

// Obtener información del docente
$conn = conectarDB();
$user_id = $_SESSION['user_id'];

// Obtener detalles del docente
$stmt = $conn->prepare("SELECT * FROM usuarios WHERE id = ? AND role = 'docente'");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$docente = $stmt->get_result()->fetch_assoc();
$fullNameDocente = $docente['apellidos'] . ', ' . $docente['nombres'];
?>
<script>
  window.phpData = {
    fullNameDocente: <?php echo json_encode($fullNameDocente); ?>
  };
</script>

<?php
// Obtener clases asignadas al docente
$stmt = $conn->prepare("
    SELECT c.id, a.nombre AS asignatura, CONCAT(pe.nombre_corto, ' - ', ci.id, ' - ', s.año) AS seccion
    FROM clases c
    JOIN asignaturas a ON c.id_asignatura = a.id
    JOIN secciones s ON c.id_seccion = s.id
    JOIN programas_estudio pe ON s.id_programa_estudio = pe.id
    JOIN ciclos ci ON s.id_ciclo = ci.id
    WHERE c.id_docente = ?
");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$clases = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$conn->close();

// Inicio del contenido
ob_start();
?>
<div class="container-fluid mt-4">
  <h1 class="mb-4">Bienvenido, <?php echo htmlspecialchars($fullNameDocente); ?></h1>

  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <i class="fas fa-book me-2"></i>Mis Clases
        </div>
        <div class="card-body">
          <table id="clasesTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <tr>
                <th>Unidad didáctica</th>
                <th>Sección</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($clases as $clase): ?>
                <tr class="clase-item" data-clase-id="<?= $clase['id'] ?>">
                  <td><?php echo htmlspecialchars($clase['asignatura']); ?></td>
                  <td><?php echo htmlspecialchars($clase['seccion']); ?></td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <i class="fas fa-clock me-2"></i>Asistencias
        </div>
        <div class="card-body" id="listaAsistencias">
          <span class="fw-semibold">Seleccione una UD para ver las asistencias.</span>
          <table id="asistenciasTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <!-- The header will be dynamically generated by JavaScript -->
            </thead>
            <tbody>
              <!-- The body will be dynamically populated by JavaScript -->
            </tbody>
          </table>


        </div>
      </div>
    </div>
  </div>
</div>

<?php
$content = ob_get_clean();

$pageScripts = '

<script src="docentes-dashboard.js"></script>
';

// Incluir el layout principal
require_once '../layouts/main.php';
?>